imports-local:
  # 'https://analytic-transparency.surroundaustralia.github.io/': '../analytic-transparency/'
  'https://analytic-transparency.surroundaustralia.github.io/': 'https://vigilant-adventure-g6z66n1.pages.github.io/build/register.json'