[package]
name = "kg-ui-toolkit"
version = "0.1.0"
edition = "2021"
description = "Reusable components of the Rust toolkit for reuse in applications"
readme = "README.md"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
geo = { workspace = true }
geo-svg = { workspace = true }
geojson = { workspace = true, features = ["geo-types"] }
gloo-dialogs = { workspace = true }
gloo-net = { workspace = true }
implicit-clone = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
web-sys = { workspace = true, features = [ "HtmlAnchorElement" ] }
yew = { workspace = true, features = ["csr"] }
yew-chart = { workspace = true }
oxigraph = { git = "https://github.com/OpenWork-NZ/oxigraph.git", rev="92a4beee5138b0981cf65fec5a8e90fc1166f463", version = "*", default-features = false }
