use implicit_clone::unsync::IString;
use web_sys::{wasm_bindgen::JsCast, HtmlAnchorElement};
use yew::prelude::*;

use crate::models;

pub enum Message {
    EntityClicked(IString),
}

#[derive(Properties, PartialEq)]
pub struct Props {
    pub entity: models::Entity,
    #[prop_or_default]
    pub on_entity_click: Option<Callback<IString>>,
}

pub struct Entity;

impl Component for Entity {
    type Message = Message;

    type Properties = Props;

    fn create(_ctx: &Context<Self>) -> Self {
        Self
    }

    fn update(&mut self, ctx: &Context<Self>, msg: Self::Message) -> bool {
        match msg {
            Message::EntityClicked(entity_id) => {
                if let Some(on_entity_click) = &ctx.props().on_entity_click {
                    on_entity_click.emit(entity_id);
                }
                false
            }
        }
    }

    fn view(&self, ctx: &Context<Self>) -> Html {
        let onclick = ctx.link().batch_callback(|event: MouseEvent| {
            event.prevent_default();
            event.target().and_then(|event_target| {
                event_target
                    .dyn_into::<HtmlAnchorElement>()
                    .ok()
                    .map(|element| Message::EntityClicked(element.href().into()))
            })
        });

        html! {
            <form>
                <fieldset>
                    <legend>{format!("Entity: {}", ctx.props().entity.label.clone().unwrap_or(AttrValue::from("<unknown>")))}</legend>
                    if let Some(value) = &ctx.props().entity.value {
                        <label for="value">{ctx.props().entity.value_label.clone().unwrap_or(AttrValue::from("Value"))}</label>
                        <input id="value" type="text" readonly=true value={value} />
                    }
                    {
                        ctx.props().entity.was_derived_from.iter().enumerate().map(|(i, link)| {
                            let id = format!("was-derived-from-{i}");
                            html! {
                                <>
                                <label for={id.clone()}>{"Derived from"}</label>
                                <a key={id.clone()} id={id} href={link.1.clone()} onclick={onclick.clone()}>{link.0.clone().unwrap_or(link.1.clone())}</a>
                                </>
                            }
                        }).collect::<Html>()
                    }
                    {
                        ctx.props().entity.was_generated_by.iter().enumerate().map(|(i, link)| {
                            let id = format!("was-generated-by-{i}");
                            html! {
                                <>
                                <label for={id.clone()}>{"Generated by"}</label>
                                <a key={id.clone()} id={id} href={link.1.clone()} onclick={onclick.clone()}>{link.0.clone().unwrap_or(link.1.clone())}</a>
                                </>
                            }
                        }).collect::<Html>()
                    }
                    {
                        ctx.props().entity.was_influenced_by.iter().enumerate().map(|(i, link)| {
                            let id = format!("was-influenced-by-{i}");
                            html! {
                                <>
                                <label for={id.clone()}>{"Influenced by"}</label>
                                <a key={id.clone()} id={id} href={link.1.clone()} onclick={onclick.clone()}>{link.0.clone().unwrap_or(link.1.clone())}</a>
                                </>
                            }
                        }).collect::<Html>()
                    }
                </fieldset>
            </form>
        }
    }
}
